/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DiffRouteImport } from './routes/diff'
import { Route as ReadRouteImport } from './routes/read'
import { Route as EditMdxeditorRouteImport } from './routes/edit.mdxeditor'
import { Route as EditPlateRouteImport } from './routes/edit.plate'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DiffRoute = DiffRouteImport.update({
  id: '/diff',
  path: '/diff',
  getParentRoute: () => rootRouteImport,
} as any)
const ReadRoute = ReadRouteImport.update({
  id: '/read',
  path: '/read',
  getParentRoute: () => rootRouteImport,
} as any)
const EditMdxeditorRoute = EditMdxeditorRouteImport.update({
  id: '/edit/mdxeditor',
  path: '/edit/mdxeditor',
  getParentRoute: () => rootRouteImport,
} as any)
const EditPlateRoute = EditPlateRouteImport.update({
  id: '/edit/plate',
  path: '/edit/plate',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/diff': typeof DiffRoute
  '/read': typeof ReadRoute
  '/edit/mdxeditor': typeof EditMdxeditorRoute
  '/edit/plate': typeof EditPlateRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/diff': typeof DiffRoute
  '/read': typeof ReadRoute
  '/edit/mdxeditor': typeof EditMdxeditorRoute
  '/edit/plate': typeof EditPlateRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/diff': typeof DiffRoute
  '/read': typeof ReadRoute
  '/edit/mdxeditor': typeof EditMdxeditorRoute
  '/edit/plate': typeof EditPlateRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/diff' | '/read' | '/edit/mdxeditor' | '/edit/plate'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/diff' | '/read' | '/edit/mdxeditor' | '/edit/plate'
  id: '__root__' | '/' | '/diff' | '/read' | '/edit/mdxeditor' | '/edit/plate'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DiffRoute: typeof DiffRoute
  ReadRoute: typeof ReadRoute
  EditMdxeditorRoute: typeof EditMdxeditorRoute
  EditPlateRoute: typeof EditPlateRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diff': {
      id: '/diff'
      path: '/diff'
      fullPath: '/diff'
      preLoaderRoute: typeof DiffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/read': {
      id: '/read'
      path: '/read'
      fullPath: '/read'
      preLoaderRoute: typeof ReadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/edit/mdxeditor': {
      id: '/edit/mdxeditor'
      path: '/edit/mdxeditor'
      fullPath: '/edit/mdxeditor'
      preLoaderRoute: typeof EditMdxeditorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/edit/plate': {
      id: '/edit/plate'
      path: '/edit/plate'
      fullPath: '/edit/plate'
      preLoaderRoute: typeof EditPlateRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DiffRoute: DiffRoute,
  ReadRoute: ReadRoute,
  EditMdxeditorRoute: EditMdxeditorRoute,
  EditPlateRoute: EditPlateRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
